### ISSUE TITLE
Incorrect SW filter mask when using LW coronagraph generated by make_psfmasks.py

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#184]
Generated mask files for the SW filters are not accurate when using a LW coronagraph. In this situation the field of view is compressed to 320x320 pixels and the ND squares are not visible. Nevertheless, these squares are present in the spaceKLIP generated masks and the coronagraph transmission also seems too focused. See attached images of Jdocs vs spaceKLIP. 

Suggest removing hardcoding of file names in `make_psfmasks.py`, or at a minimum updating them to the current valid files. 

Seems that many of the psfmask files are hardcoded, and may be out of date, driving this issue. 
![image (7)](https://github.com/kammerje/spaceKLIP/assets/23636747/4cb643c4-52c0-416b-ab87-d5f5119df6f4)
![image (8)](https://github.com/kammerje/spaceKLIP/assets/23636747/5db41803-bd99-4784-89bb-9869338e5e1a)

**Comment by kammerje** [comment]
I saw that the PSF mask files on CRDS have been updated now so that we can pull them directly from there. This makes the entire `make_psfmasks.py` file obsolete (I suggest we remove it from the repo eventually) and simplifies the installation of `spaceKLIP`. I tested this on the ERS data and some of @AarynnCarter's new data and it worked correctly.

Fixed with [this](https://github.com/kammerje/spaceKLIP/commit/4753265f031020c059cd5ffd0f5f69d27d6b1bc6) commit.
