### ISSUE TITLE
Tidy up terminal printing 

### ISSUE THREAD

**Issue by AarynnCarter** [kammerje/spaceKLIP#24]
Current code generates the same log message over and over: 

```
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
WebbPSF log messages of level ERROR and above will be shown.
```

Would be nice to get rid of this entirely.

**Comment by mperrin** [comment]
Looking at logging display in the current (new) spaceKLIP, it appears that the import of `webbpsf_ext` has a side effect of configuring more verbose logging (whether you want this or not). Here's a very simple test case which shows that. There's text output from `webbpsf` after importing `webbpsf_ext,` but not before. 


![Screenshot 2023-07-28 at 12 52 16 PM](https://github.com/kammerje/spaceKLIP/assets/1151745/6673a640-6e5e-49ac-900c-a1c4d0be8572)

@JarronL I presume this is intentional on your part, but is there some way to disable this if it's an undesired side effect?

**Comment by JarronL** [comment]
yeah, INFO is the default logging level. You can update to warnings: `webbpsf_ext.setup_logging('WARN', verbose=False)`

**Comment by JarronL** [comment]
Okay, I think the original issue has already been fixed. It used to be that logging levels were set via `webbpsf.setup_logging(level='ERROR')` which always prints out statements like:

```
WebbPSF log messages of level ERROR and above will be shown.
WebbPSF log outputs will be directed to the screen.
```

I have since changed this to `webbpsf_ext.setup_logging(level='ERROR', verbose=False)`, which includes updating the logging levels of poppy, webbpsf, and webbpsf_ext. But with `verbose=False`, it no longer prints those log values.
